# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fedd7b8a44b764aeee6dece65e3b795a2833be2a2f220b3f8f14f6ec5292aa6d4e769ce1e046cf7d91bab89fc8e38f3c942fbe0ded4b1ebf859d2d56930cfe0

test:
  secret_key_base: 02a1c756b3cf6afd5338c54ed6c1268ad0c9da40ffbc4c59f087a1e4a2d27515ac839fce8f1ca0d7904a3a5618cf6ad85232ba05b485440bbb0f7ec9510f9b5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
